dataset:
  name: wayne_crop
  preprocess: false
  raw_images: /home/omar/projects/unc/PHASER/data/phaser_rpe/raw/images
  raw_labels: /home/omar/projects/unc/PHASER/data/phaser_rpe/labels_original.csv
  channel_annot: /home/omar/projects/unc/PHASER/data/phaser_rpe/channel_annotations.csv
  data_dir: /home/omar/projects/unc/PHASER/data/phaser_rpe/processed/dynamic_crop
  labels: /home/omar/projects/unc/PHASER/data/phaser_rpe/processed/labels.csv
  channels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 47
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  args:
    train:
      split: 0.6
      shuffle: true
      balance: up
      augment: false
      mask: null
      fill: false
      log_image: 10
    val:
      split: 0.2
      shuffle: true
      balance: null
      augment: false
      mask: null
      fill: false
      log_image: 10
    test:
      split: 0.2
      shuffle: true
      balance: null
      augment: false
      mask: null
      fill: false
      log_image: 10
model:
  name: rotation_net
  add_regressor: false
  architecture: cnn
  num_conv_layers: 2
  filters:
  - 55
  - 110
  - 220
  conv_kernel_size: 3
  conv_padding: same
  conv_activation: relu
  conv_strides: 1
  pool: avg
  pool_size: 2
  pool_padding: valid
  pool_strides: 2
  pair_convs: true
  dropout: 0.5
  num_dense_layers: 2
  dense_neurons:
  - 128
  - 64
  dense_activation: relu
  pair_dropout: true
  initializer: he_normal
mode:
  name: train
  test_data_out: data/phaser_rpe/results
  epochs: 10
  batch_size: 10
  loss: categorical_crossentropy
  metrics:
  - categorical_accuracy
  metric_names:
  - Categorical Accuracy
  optimizer: adam
  optimizer_args:
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 1.0e-07
  early_stopping:
    enabled: true
    monitor: val_loss
    patience: 3
random_seed: 416
force_gpu: true
model_save_path: saved_models/
save_model: true
results_save_path: results/
wandb:
  project: PHASER
  group: ${model.name}_${dataset.name}
  name: defaults_dna_only
  entity: oem
