# Training parameters
epochs: 20
batch_size: 20
loss: 'CrossEntropy'
metric: 'CategoricalAccuracy'
optimizer: 'adam'
learning_rate: 0.001
data_shuffle: true

early_stopping:
  enabled: true
  patience: 3