name: train

test_data_out: data/phaser_rpe/results  # Where to save test data

# Training parameters
epochs: 20
batch_size: 20
loss: 'categorical_crossentropy'        # standard tf loss or custom loss
metrics: ['categorical_accuracy']
metric_names: ['Categorical Accuracy']  # len must match metrics
optimizer: 'adam'
learning_rate: 0.001
data_shuffle: true

early_stopping:
  enabled: true
  patience: 3