defaults:
  - dataset: wayne_crop
  - model: alexnet
  - mode: train
  - _self_

random_seed: 416
force_gpu: true  # Will stop the program if GPU not detected

model_save_path: saved_models/
results_save_path: results/

wandb:
  project: PHASER
  group: ${model.name}_${dataset.name}
  name: cropped_dataset
  entity: oem
