wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724702506
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.12.3
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
