defaults:
  - dataset: wayne_crop_inference_rem
  - model: alexnet_royal
  - mode: inference
  - _self_

random_seed: 416
force_gpu: true  # Will stop the program if GPU not detected

wandb:
  project: PHASER
  group: ${model.name}_${dataset.name}
  name: alexnet_incl_test_set
  entity: oem
  tags:
    - ${model.name}
    - ${dataset.name}
    - ${mode.name}