defaults:
  - dataset: wayne_rpe
  - model: rotation_net
  - optimizer: adam
  - _self_

mode: train
random_seed: 416
skip_gpu_check: true

wandb:
  project: PHASER
  group: ${model.name}
  run_name: default_run
  tags: null

hydra:
  run:
    dir: .
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: CRITICAL
      handlers: [console]