version: 1
disable_existing_loggers: true

formatters:
  simple:
    format: '%(asctime)s %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: placeholder.log

loggers:
  root:
    level: INFO
    handlers: [console, file]