wandb_version: 1

cell_phase_preds:
  value: /media/omar/1354B7D111621BC0/projects/unc/wayne_rpe/data/labels_original.csv
cells_df:
  value: /media/omar/1354B7D111621BC0/projects/unc/wayne_rpe/data/full_df.csv
features:
  value: /media/omar/1354B7D111621BC0/projects/unc/wayne_rpe/data/feature_df_v6_noIntgStdOver.csv
gamma:
  value: 0.07186258894216802
knn:
  value: 322
n_features:
  value: 157.53179973937364
rank_by:
  value: rank
t:
  value: 20
z_score:
  value: true
