name: 'rotation_net'
save_path: 'saved_models/rotation_net/'

# Training parameters
train:
  epochs: 20
  batch_size: 20
  loss: 'CrossEntropy'
  metric: 'CategoricalAccuracy'
  initializer:
    name: 'he_normal'
    mode: 'fan_out'
    nonlinearity: 'relu'

# Misc
add_regressor: false # adds a single neuron output to the model for pred_age

# Model architecture 
# note output layer is added automatically based on the number of classes 
# in the dataset, do not include it here.
layers:
  - type: "Conv2D"
    name: "Conv1"
    out: 55 
    kernel_size: 7
    padding: 'same'
    stride: 1
    activation: 'relu'

  - type: "AvgPool2D"
    name: "Pool1"
    pool_size: 2
    stride: 2

  - type: "Conv2D"
    name: "Conv2"
    out: 110
    kernel_size: 3
    padding: 'same'
    stride: 1
    activation: 'relu'

  - type: "Conv2D"
    name: "Conv3"
    out: 110
    kernel_size: 3
    padding: 'same'
    stride: 1
    activation: 'relu'

  - type: "AvgPool2D"
    name: "Pool2"
    pool_size: 2
    stride: 2

  - type: "Conv2D"
    name: "Conv4"
    out: 220
    kernel_size: 3
    padding: 'same'
    stride: 1
    activation: 'relu'

  - type: "Conv2D"
    name: "Conv5"
    out: 220
    kernel_size: 3
    padding: 'same'
    stride: 1
    activation: 'relu'

  - type: "AvgPool2D"  
    name: "Pool3"
    pool_size: 2
    stride: 2

  - type: "Flatten"
    name: "Flatten"

  - type: "Dense"
    name: "Dense1"
    out: 128
    activation: 'relu'

  - type: "Dropout"
    name: "Dropout1"
    rate: 0.5

  - type: "Dense"
    name: "Dense2"
    out: 64
    activation: 'relu'

  - type: "Dropout"
    name: "Dropout2"
    rate: 0.5