name: train

# Training parameters
epochs: 15
batch_size: 24
loss: 'categorical_crossentropy'        # standard tf loss or custom loss
metrics: 'categorical_accuracy'
metric_names: 'Categorical Accuracy'  # len must match metrics

optimizer: 'adam'
optimizer_args:
  learning_rate: 0.01383809597087758
  beta_1: 0.9489838374721248
  beta_2: 0.9958173159550412
  epsilon: 0.061056

early_stopping:
  enabled: true
  patience: 3
  min_epochs: 3

save_model:
  enabled: true
  path: /work/users/o/e/oem/PHASER/saved_models/

save_test_results:
  enabled: true 
  path: /work/users/o/e/oem/PHASER/results/