wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724777490
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.12.3
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
cell_phase_preds:
  desc: null
  value: /media/omar/1354B7D111621BC0/projects/unc/wayne_rpe/data/labels_original.csv
cells_df:
  desc: null
  value: /media/omar/1354B7D111621BC0/projects/unc/wayne_rpe/data/full_df.csv
features:
  desc: null
  value: /media/omar/1354B7D111621BC0/projects/unc/wayne_rpe/data/feature_df_v6_noIntgStdOver.csv
gamma:
  desc: null
  value: -0.1898771035402571
knn:
  desc: null
  value: 72
n_features:
  desc: null
  value: 80
rank_by:
  desc: null
  value: rank
t:
  desc: null
  value: 24
z_score:
  desc: null
  value: true
