defaults:
  - dataset: wayne_rpe
  - model: rotation_net
  - mode: train
  - _self_

random_seed: 416
force_gpu: true  # Will stop the program if GPU not detected

wandb:
  project: PHASER
  group: ${model.name}_${dataset.name}
  run_name: defaults_dsktp

hydra:
  run:
    dir: 'logs/${model.name}/${now:%Y-%m-%d}/'
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s %(levelname)s: %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${now:%H%M%S}_${wandb.run_name}.log
    root:
      level: INFO
      handlers: [console, file]